### ISSUE TITLE
ccw.repl.REPLView cannot be cast to org.eclipse.swt.custom.LineStyleListener

### ISSUE THREAD

**Issue by smee** [laurentpetit/ccw-plugin-ansi-repl#1]
I started a REPL on Windows, Java 1.8.0, CCW 0.31.1.STABLE001, clicked on the URL in the console `nREPL server started on port 27663 on host 127.0.0.1 - nrepl://127.0.0.1:27663`
CCW-Pluginmanager was installed, this plugin as well. No other plugins are present

I saw this error message:
![image](https://cloud.githubusercontent.com/assets/36397/7512834/0db0e684-f4b0-11e4-8b35-675f68dbfe87.png)

Tests like 

``` clojure
(println (str "\u001B[31m" "test" "\u001B[0m"))
```

did not result in colored output.

**Comment by laurentpetit** [comment]
Indeed. The Pull Request adding LineStyleListener interface to REPLView hasn't been merged to CCW master yet. Will be before the next release, though. Will add a note to the README.

**Comment by laurentpetit** [comment]
Should be released into master ( and thus available through http://updatesite.ccw-ide.org/branch/master/ ) by the end of the day if reviews work well

**Comment by laurentpetit** [comment]
This is actually really annoying. Will fix the issue so the user plugin can be installed, quietly ignored for a while, and become active when it detects the relevant version of Counterclockwise.

**Comment by smee** [comment]
Thanks!

**Comment by laurentpetit** [comment]
Now the plugin compilation will throw an exception, which will be logged, but not produce a popup.
